<?php
/**
 * Plugin Name: Snow Fall Effect
 * Plugin URI: https://yourwebsite.com/
 * Description: Adds a beautiful snowfall effect to your WordPress site
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 * Text Domain: snow-fall-effect
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

class SnowFallEffect {
    
    public function __construct() {
        // Hook into WordPress
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'create_settings_page'));
        add_action('admin_init', array($this, 'register_settings'));
        add_filter('plugin_action_links_' . plugin_basename(__FILE__), array($this, 'add_settings_link'));
        
        // Add snow effect to footer
        add_action('wp_footer', array($this, 'render_snow_effect'), 100);
    }
    
    /**
     * Enqueue scripts and styles
     */
    public function enqueue_scripts() {
        // Only enqueue on front-end
        if (is_admin()) {
            return;
        }
        
        // Enqueue CSS
        wp_enqueue_style(
            'snow-fall-effect-css',
            plugin_dir_url(__FILE__) . 'css/snow-fall-effect.css',
            array(),
            '1.0.0'
        );
        
        // Enqueue JavaScript
        wp_enqueue_script(
            'snow-fall-effect-js',
            plugin_dir_url(__FILE__) . 'js/snow-fall-effect.js',
            array(),
            '1.0.0',
            true
        );
        
        // Pass settings to JavaScript
        wp_localize_script('snow-fall-effect-js', 'snowSettings', array(
            'snowflakeCount' => get_option('snow_flake_count', 100),
            'snowflakeSpeed' => get_option('snow_speed', 1),
            'snowflakeSize' => get_option('snow_size', 2),
            'snowflakeColor' => get_option('snow_color', '#ffffff'),
            'snowflakeCharacter' => get_option('snow_character', '❄'),
            'enableOnMobile' => get_option('snow_mobile_enable', 'no'),
            'onlyWinter' => get_option('snow_only_winter', 'no'),
            'zIndex' => get_option('snow_zindex', 9998)
        ));
    }
    
    /**
     * Render snow effect in footer
     */
    public function render_snow_effect() {
        // Check if we should show snow
        if (!$this->should_show_snow()) {
            return;
        }
        
        // Create snow container
        echo '<div id="snow-container" class="snow-container"></div>';
    }
    
    /**
     * Check if snow should be displayed
     */
    private function should_show_snow() {
        // Don't show in admin
        if (is_admin()) {
            return false;
        }
        
        // Check mobile setting
        $enableOnMobile = get_option('snow_mobile_enable', 'no');
        if (wp_is_mobile() && $enableOnMobile !== 'yes') {
            return false;
        }
        
        // Check winter months setting
        $onlyWinter = get_option('snow_only_winter', 'no');
        if ($onlyWinter === 'yes') {
            $currentMonth = date('n');
            // Only show in December, January, February
            if (!in_array($currentMonth, [12, 1, 2])) {
                return false;
            }
        }
        
        return true;
    }
    
    /**
     * Create settings page in admin
     */
    public function create_settings_page() {
        add_options_page(
            'Snow Fall Effect Settings',
            'Snow Fall Effect',
            'manage_options',
            'snow-fall-effect',
            array($this, 'settings_page_html')
        );
    }
    
    /**
     * Settings page HTML
     */
    public function settings_page_html() {
        // Check user capabilities
        if (!current_user_can('manage_options')) {
            return;
        }
        
        ?>
        <div class="wrap">
            <h1><?php echo esc_html(get_admin_page_title()); ?></h1>
            <form action="options.php" method="post">
                <?php
                settings_fields('snow_fall_effect');
                do_settings_sections('snow-fall-effect');
                submit_button('Save Settings');
                ?>
            </form>
            
            <div class="snow-preview" style="margin-top: 30px; padding: 20px; background: #1e1e1e; border-radius: 5px;">
                <h3>Preview</h3>
                <p>The snow effect will be visible on your site's front-end. Below is a small preview:</p>
                <div id="snow-preview" style="height: 200px; position: relative; overflow: hidden; border: 1px solid #333;">
                    <!-- Preview will be generated by JavaScript -->
                </div>
                <p><small>Note: This is a simplified preview. The actual effect may vary.</small></p>
            </div>
        </div>
        <?php
    }
    
    /**
     * Register settings
     */
    public function register_settings() {
        // Register settings
        register_setting('snow_fall_effect', 'snow_flake_count');
        register_setting('snow_fall_effect', 'snow_speed');
        register_setting('snow_fall_effect', 'snow_size');
        register_setting('snow_fall_effect', 'snow_color');
        register_setting('snow_fall_effect', 'snow_character');
        register_setting('snow_fall_effect', 'snow_mobile_enable');
        register_setting('snow_fall_effect', 'snow_only_winter');
        register_setting('snow_fall_effect', 'snow_zindex');
        
        // Add settings section
        add_settings_section(
            'snow_fall_effect_section',
            'Snow Effect Configuration',
            null,
            'snow-fall-effect'
        );
        
        // Add settings fields
        $this->add_settings_field('snow_flake_count', 'Number of Snowflakes', 'number', '100', 'Number of snowflakes to display (1-500)');
        $this->add_settings_field('snow_speed', 'Snowfall Speed', 'range', '1', 'Speed of snowfall (0.1 - 5)', 0.1, 5, 0.1);
        $this->add_settings_field('snow_size', 'Snowflake Size', 'range', '2', 'Size of snowflakes in pixels (1-10)', 1, 10, 1);
        $this->add_settings_field('snow_color', 'Snowflake Color', 'color', '#ffffff', 'Color of snowflakes');
        $this->add_settings_field('snow_character', 'Snowflake Character', 'text', '❄', 'Character to use as snowflake (emoji or text)');
        $this->add_settings_field('snow_mobile_enable', 'Enable on Mobile', 'checkbox', 'no', 'Show snow effect on mobile devices');
        $this->add_settings_field('snow_only_winter', 'Winter Months Only', 'checkbox', 'no', 'Show snow only in December, January, February');
        $this->add_settings_field('snow_zindex', 'Z-Index', 'number', '9998', 'CSS z-index value (lower values appear behind content)');
    }
    
    /**
     * Helper to add settings fields
     */
    private function add_settings_field($id, $title, $type, $default, $description = '', $min = null, $max = null, $step = null) {
        add_settings_field(
            $id,
            $title,
            function() use ($id, $type, $default, $description, $min, $max, $step) {
                $value = get_option($id, $default);
                
                switch ($type) {
                    case 'number':
                        echo '<input type="number" id="' . esc_attr($id) . '" name="' . esc_attr($id) . '" value="' . esc_attr($value) . '" class="regular-text"';
                        if ($min !== null) echo ' min="' . esc_attr($min) . '"';
                        if ($max !== null) echo ' max="' . esc_attr($max) . '"';
                        if ($step !== null) echo ' step="' . esc_attr($step) . '"';
                        echo '>';
                        break;
                        
                    case 'range':
                        echo '<input type="range" id="' . esc_attr($id) . '" name="' . esc_attr($id) . '" value="' . esc_attr($value) . '"';
                        if ($min !== null) echo ' min="' . esc_attr($min) . '"';
                        if ($max !== null) echo ' max="' . esc_attr($max) . '"';
                        if ($step !== null) echo ' step="' . esc_attr($step) . '"';
                        echo ' style="width: 300px;">';
                        echo '<span id="' . esc_attr($id) . '_value">' . esc_html($value) . '</span>';
                        echo '<script>document.getElementById("' . esc_js($id) . '").addEventListener("input", function(e) { document.getElementById("' . esc_js($id) . '_value").textContent = e.target.value; });</script>';
                        break;
                        
                    case 'color':
                        echo '<input type="color" id="' . esc_attr($id) . '" name="' . esc_attr($id) . '" value="' . esc_attr($value) . '">';
                        break;
                        
                    case 'checkbox':
                        echo '<input type="checkbox" id="' . esc_attr($id) . '" name="' . esc_attr($id) . '" value="yes"' . checked($value, 'yes', false) . '>';
                        break;
                        
                    case 'text':
                    default:
                        echo '<input type="text" id="' . esc_attr($id) . '" name="' . esc_attr($id) . '" value="' . esc_attr($value) . '" class="regular-text">';
                        break;
                }
                
                if ($description) {
                    echo '<p class="description">' . esc_html($description) . '</p>';
                }
            },
            'snow-fall-effect',
            'snow_fall_effect_section'
        );
    }
    
    /**
     * Add settings link on plugins page
     */
    public function add_settings_link($links) {
        $settings_link = '<a href="' . admin_url('options-general.php?page=snow-fall-effect') . '">' . __('Settings') . '</a>';
        array_unshift($links, $settings_link);
        return $links;
    }
}

// Initialize the plugin
new SnowFallEffect();
